package org.apache.usergrid.apm.model;

public class EventConstants {
	public static String SESSION_EVENT_TAG = "SESSION_EVENT";
	public static String SESSION_EVENT_APPLICATION_START = "APPLICATION_STARTED";
	public static String SESSION_EVENT_APPLICATION_STOP = "APPLICATION_STOPPED";
	public static String SESSION_EVENT_APPLICATION_PAUSED = "APPLICATION_PAUSED";
	public static String SESSION_EVENT_APPLICATION_RESUMED = "APPLICATION_RESUMED";
	public static String SESSION_EVENT_APPLICATION_CRASH = "APPLICATION_CRASHED";
	public static String SESSION_EVENT_USER_ACTIVITY_DETECTED = "USER_ACTIVITY_DETECTED";
}