;;
;; Licensed to the Apache Software Foundation (ASF) under one or more
;; contributor license agreements.  See the NOTICE file distributed with
;; this work for additional information regarding copyright ownership.
;; The ASF licenses this file to You under the Apache License, Version 2.0
;; (the "License"); you may not use this file except in compliance with
;; the License.  You may obtain a copy of the License at
;;
;;     http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.
;;

;;
;; If you've installed Nu (http://github.com/timburks/nu),
;; then you can build the Usergrid SDK as a Mac framework
;; by typing "nuke" in this directory. Type "nuke install"
;; to install it in /Library/Frameworks.
;; 
(set @m_files (filelist "^UGAPI/.*.m$"))
(@m_files addObjectsFromSet:(filelist "^UGAPI/SBJSON/.*.m$"))
(@m_files addObjectsFromSet:(filelist "^UGAPI/v2/.*.m$"))

(set @arch '("x86_64"))

;; framework description
(set @framework "Usergrid")
(set @framework_identifier "com.apigee.usergrid")

(set @cc "clang")
(set @cflags "-fobjc-arc -I UGAPI -I UGAPI/SBJSON -I UGAPI/v2")
(set @ldflags  "-framework Foundation ")

(compilation-tasks)
(framework-tasks)

(task "clobber" => "clean" is
      (SH "rm -rf #{@framework_dir}"))

(task "default" => "framework")


