#!/bin/sh

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO make this a real script that can be executed from any directory

VERSION=`grep '<parent>' -A 4 pom.xml | grep version | sed -e 's/ *<[\/]*version>//g'`
JVM_OPTS='-Djava.library.path=/tmp -Dorg.xerial.snappy.tempdir=/tmp'

if [ "$1" == "debug" ]; then
  JVM_OPTS="$JVM_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005"
fi

java -jar $JVM_OPTS target/usergrid-launcher-$VERSION.jar

