#created on: Apr 14, 2011
package NetworkMetricsProcessor

import org.apache.usergrid.apm.model.*;
import org.apache.usergrid.apm.model.*;
import java.util.*;
import org.apache.usergrid.apm.service.charts.service.SessionChartCriteriaService;
import org.apache.usergrid.apm.service.charts.service.NetworkMetricsChartCriteriaService;
import org.apache.usergrid.apm.service.charts.service.LogChartCriteriaService;


global org.apache.commons.logging.Log log;

global	List dirtySummarySessionMetrics;	
global	List dirtyCompactClientLog;
global	List dirtyCompactSessionMetrics;
global	List dirtyCompactNetworkMetrics;

global SessionChartCriteriaService sessionChartCriteriaService;
global NetworkMetricsChartCriteriaService networkMetricsChartCriteriaService;
global LogChartCriteriaService logChartCriteriaService;

dialect "java"

declare NetworkMetricsCarrier
	type: String
end

rule "NetworkMetricsCarrierRule_PoorPerf"
	no-loop true
when 
	$nm : ClientNetworkMetrics( $networkCarrier : networkCarrier,maxLatency >NetworkMetricsChartCriteriaService.LARGE_LATENCY_THRESHOLD ) from entry-point "clientNetworkMetricsStream"
	not (exists NetworkMetricsCarrier(type == $networkCarrier))
then	
	insert( new NetworkMetricsCarrier($networkCarrier));
end



rule "CompactNetworkMetricCarrierGenerator_PoorPerf"
when
 $networkCarrier : NetworkMetricsCarrier()
 $nm : ClientNetworkMetrics(endMinute != null,maxLatency >NetworkMetricsChartCriteriaService.LARGE_LATENCY_THRESHOLD) from entry-point "clientNetworkMetricsStream"
 not (exists (CompactNetworkMetrics(appId == $nm.appId,endMinute == $nm.endMinute,
     networkCarrier ==$networkCarrier.type) from entry-point "compactNetworkMetricsStream_ByCarrier_PoorPerf"))
then
 log.info("Detected new ClientNetworkMetrics to trigger new CompactNetworkMetricsCarrierGenerator_PoorPerf : " +  $nm.getEndMinute() + " AppID: " + $nm.getAppId()); 
   
 CompactNetworkMetrics metric = new CompactNetworkMetrics();
 metric.setTimeStamp(new Date( $nm.getEndMinute() * 1000 * 60));
 metric.setNetworkCarrier($networkCarrier.getType());
 metric.setAppId($nm.getAppId());
 metric.setSamplePeriod(ChartCriteria.SamplePeriod.MINUTE);
 Long id = networkMetricsChartCriteriaService.getDefaultChartCriteriaByName( $nm.getAppId(), NetworkMetricsChartCriteriaService.POOR_NETWORK_PERFORMANCE_BY_CARRIER).getId();
 metric.setChartCriteriaId(id);
 
 entryPoints["compactNetworkMetricsStream_ByCarrier_PoorPerf"].insert(metric);
end


rule "CompactNetworkMetricsCarrierCalculator_PoorPerf"
   salience -200
   no-loop true
when
 $metric : CompactNetworkMetrics() from entry-point "compactNetworkMetricsStream_ByCarrier_PoorPerf" 
 $sumNumSamples : Number() 
	from accumulate (ClientNetworkMetrics(appId == $metric.appId, endMinute == $metric.endMinute, maxLatency >NetworkMetricsChartCriteriaService.LARGE_LATENCY_THRESHOLD, networkCarrier == $metric.networkCarrier, $numSamples : numSamples )
		from entry-point "clientNetworkMetricsStream" , sum($numSamples))
 $sumNumErrors : Number() 
	from accumulate (ClientNetworkMetrics(appId == $metric.appId, endMinute == $metric.endMinute, maxLatency >NetworkMetricsChartCriteriaService.LARGE_LATENCY_THRESHOLD, networkCarrier == $metric.networkCarrier,$numErrors : numErrors )
		from entry-point "clientNetworkMetricsStream" , sum($numErrors))
 $sumSumLatency : Number() 
	from accumulate (ClientNetworkMetrics(appId == $metric.appId, endMinute == $metric.endMinute, maxLatency >NetworkMetricsChartCriteriaService.LARGE_LATENCY_THRESHOLD, networkCarrier == $metric.networkCarrier,$sumLatency : sumLatency )
		from entry-point "clientNetworkMetricsStream" , sum($sumLatency))
 $minMinLatency : Number() 
	from accumulate (ClientNetworkMetrics(appId == $metric.appId, endMinute == $metric.endMinute, maxLatency >NetworkMetricsChartCriteriaService.LARGE_LATENCY_THRESHOLD, networkCarrier == $metric.networkCarrier,$minLatency : minLatency )
		from entry-point "clientNetworkMetricsStream" , min($minLatency))
 $maxMaxLatency : Number() 
	from accumulate (ClientNetworkMetrics(appId == $metric.appId, endMinute == $metric.endMinute, maxLatency >NetworkMetricsChartCriteriaService.LARGE_LATENCY_THRESHOLD, networkCarrier == $metric.networkCarrier,$maxLatency : maxLatency )
		from entry-point "clientNetworkMetricsStream" , max($maxLatency))		
then

 log.info("CompactNetworkMetricsCalculator : $numSamples | $numErrors |  $sumLatency | $minLatency | $maxLatency "
 	+ $sumNumSamples + "|" 
 	+ $sumNumErrors + "|" 
 	+ $sumSumLatency + "|" 
 	+ $minMinLatency + "|" 
 	+ $maxMaxLatency );

 modify($metric) {
 	setNumSamples(new Long($sumNumSamples.longValue())),
 	setNumErrors(new Long($sumNumErrors.longValue())),
 	setSumLatency(new Long($sumSumLatency.longValue())),
 	setMinLatency(new Long($minMinLatency.longValue())),
 	setMaxLatency(new Long($maxMaxLatency.longValue())) 	
 }
end



// Note that only metrics that have changed will get impacted.
rule "PersistModifiedCompactNetworkMetricsnetworkCarrierStream_PoorPerf"
   salience -500
when
 $metric : CompactNetworkMetrics() from entry-point "compactNetworkMetricsStream_ByCarrier_PoorPerf"
then
 log.info("Marking CompactNetworkMetrics dirty " + $metric.getId() + " Output " + $metric.toString());
 dirtyCompactNetworkMetrics.add($metric);
end

/*
Need to see if the accumulate logic can be streamlined as mentioned in
http://docs.jboss.org/drools/release/5.2.0.CR1/droolsjbpm-introduction-docs/html/ch02.html Section 2.1.1.1 Multi-function Accumulates
rule "CompactNetworkMetricsCalculator"
   salience -200
   no-loop true
when
 $metric : CompactNetworkMetrics() from entry-point "compactNetworkMetricsStream" 
 accumulate (ClientNetworkMetrics(appId == $metric.appId, endMinute == $metric.endMinute))
 	 $sumNumSamples : sum($numSamples )
 	 $minLat : min($minLatency)


*/


